### ISSUE TITLE
Xake Lint

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/xake-node#3]
Xake needs to check for:

multipleChoice without correct (error) _or_ too many (warning)
selectAll without correct _or_ a single correct (warning)

\answers or multipleChoice or freeResponse or selectAll (or anything that is answerable) that doesn't live in an environment. 

missing \maketitle

check that \answer parses

**Comment by kisonecat** [comment]
dc7039aed017521396dc116cdcb9585b1454370d does most of this, except for checking if \answer actually parses under math-expressions.
